[package]
name = "utc-telegram-bot"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.3.1"
failure = "0.1.7"
log = "0.4.8"
env_logger = "0.7.1"
tokio = { version = "0.2.13", features = ["macros", "fs"] }
futures = "0.3"
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot.git", rev = "8e363c51" }
fuzzy-matcher = "0.3.4"
rand = { version = "0.7.3", default-features = false, features = ["std", "small_rng"] }
paw = "1.0.0"
structopt = { version = "0.3.11", features = ["paw"] }

image = { version = "0.23.1", default-features = false, features = ["jpeg"], optional = true }
resvg = { version = "0.9.0", features = ["cairo-backend", "text"], optional = true }
cairo-rs = { version = "0.8.1", optional = true }
pangocairo = { version = "0.9.0", optional = true }
pango = { version = "0.8.0", optional = true }
crc = "1.8.1"
lazy_static = "1.4.0"

[features]
default = []
renderer = ["image", "resvg", "cairo-rs", "pangocairo", "pango"]
