[package]
name = "utc-telegram-bot"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.3.2"
failure = "0.1.8"
log = "0.4.14"
env_logger = "0.8.3"
tokio = { version = "1.3.0", features = ["macros", "rt"] }
futures = "0.3.13"
telegram-bot = "0.8.0"
fuzzy-matcher = "0.3.7"
rand = { version = "0.8.3", default-features = false, features = ["std", "small_rng"] }
paw = "1.0.0"
structopt = { version = "0.3.21", features = ["paw"] }

image = { version = "0.23.14", default-features = false, features = ["jpeg"], optional = true }
cairo-rs = { version = "0.9.1", optional = true }
pangocairo = { version = "0.10.0", optional = true }
pango = { version = "0.9.1", optional = true }
crc = "1.8.1"
lazy_static = "1.4.0"

[features]
default = []
renderer = ["image", "cairo-rs", "pangocairo", "pango"]
