name: build

on:
  pull_request: {}
  push:
    branches:
      - master
      - dev
    tags-ignore:
      - "**"

jobs:
  build:
    uses: vtavernier/github-workflows/.github/workflows/build-rust-docker.yml@v1.0.0-alpha.7
    with:
      develop_branch_name: dev
    secrets:
      docker_password: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
