name: build

on:
  pull_request: {}
  push:
    branches:
      - master
    tags-ignore:
      - "**"

jobs:
  build:
    uses: vtavernier/github-workflows/.github/workflows/build-rust-docker.yml@v1.0.0-alpha.8
    secrets:
      docker_password: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
