name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Dry-run semantic release first in case something is wrong
      - name: Semantic Release (Dry-Run)
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        id: semantic

      # Setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute target image labels
        run: |
          GITHUB_REF='${{ github.ref }}'
          if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
            LABEL=latest
            PUSH=true
          else
            LABEL="$(echo -n "$GITHUB_REF" | sed 's#refs/heads/##')"
            PUSH=false
          fi

          echo ::set-output name=label::"$LABEL"
          echo ::set-output name=push::"$PUSH"
          echo ::set-output name=ghcr::"ghcr.io/${{ github.actor }}/utc-telegram-bot"
          if [[ "${{ steps.semantic.outputs.new_release_published }}" == "true" ]]; then
            echo ::set-output name=ghcr_tag::"ghcr.io/${{ github.actor }}/utc-telegram-bot:${{ steps.semantic.outputs.new_release_version }}"
          else
            echo ::set-output name=ghcr_tag::
          fi
        id: image

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.image.outputs.ghcr }}:${{ steps.image.outputs.label }}
          push: ${{ steps.image.outputs.push }}

      # On master, actually run semantic release
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        if: github.ref == 'refs/heads/master'
